#!/bin/bash
# ============================================================================
# 🔊 PLUTO - Audio Auto-Setup for Raspberry Pi
# ============================================================================
# Automatically detects and configures USB microphone and speaker
# Run: chmod +x audio_setup.sh && ./audio_setup.sh
# ============================================================================

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

print_header() {
    echo ""
    echo -e "${BLUE}════════════════════════════════════════════════════════════${NC}"
    echo -e "${BLUE}  $1${NC}"
    echo -e "${BLUE}════════════════════════════════════════════════════════════${NC}"
}

print_success() { echo -e "${GREEN}✅ $1${NC}"; }
print_warning() { echo -e "${YELLOW}⚠️  $1${NC}"; }
print_error() { echo -e "${RED}❌ $1${NC}"; }
print_info() { echo -e "${CYAN}ℹ️  $1${NC}"; }

# ============================================================================
print_header "🔊 PLUTO Audio Auto-Setup"
# ============================================================================

echo ""
echo "This script will:"
echo "  1. Detect your USB microphone and speaker"
echo "  2. Configure them as default devices"
echo "  3. Test audio playback and recording"
echo ""

# ============================================================================
print_header "Step 1: Killing existing audio processes"
# ============================================================================

pulseaudio -k 2>/dev/null || true
sudo killall pulseaudio 2>/dev/null || true
sleep 1
print_success "Audio processes cleared"

# ============================================================================
print_header "Step 2: Detecting Audio Devices"
# ============================================================================

echo ""
echo -e "${CYAN}=== PLAYBACK DEVICES (Speakers) ===${NC}"
aplay -l 2>/dev/null || echo "No playback devices found"

echo ""
echo -e "${CYAN}=== RECORDING DEVICES (Microphones) ===${NC}"
arecord -l 2>/dev/null || echo "No recording devices found"

# ============================================================================
print_header "Step 3: Finding USB Audio Devices"
# ============================================================================

# Find USB playback device
USB_PLAYBACK_CARD=""
USB_PLAYBACK_NAME=""

while IFS= read -r line; do
    if [[ "$line" =~ ^card\ ([0-9]+):.*USB|usb|Audio ]]; then
        card_num="${BASH_REMATCH[1]}"
        if aplay -l 2>/dev/null | grep -q "card $card_num:"; then
            USB_PLAYBACK_CARD="$card_num"
            USB_PLAYBACK_NAME=$(echo "$line" | sed 's/card [0-9]*: //' | cut -d'[' -f2 | cut -d']' -f1)
            break
        fi
    fi
done < <(aplay -l 2>/dev/null | grep -i "card\|USB\|usb\|Audio")

# Alternative detection
if [ -z "$USB_PLAYBACK_CARD" ]; then
    # Look for any non-bcm2835 card (USB devices)
    while IFS= read -r line; do
        if [[ "$line" =~ ^card\ ([0-9]+): ]] && [[ ! "$line" =~ bcm2835 ]] && [[ ! "$line" =~ vc4 ]]; then
            USB_PLAYBACK_CARD="${BASH_REMATCH[1]}"
            USB_PLAYBACK_NAME=$(echo "$line" | sed 's/card [0-9]*: //' | cut -d'[' -f2 | cut -d']' -f1)
            break
        fi
    done < <(aplay -l 2>/dev/null)
fi

# Find USB recording device
USB_RECORD_CARD=""
USB_RECORD_NAME=""

while IFS= read -r line; do
    if [[ "$line" =~ ^card\ ([0-9]+): ]] && [[ ! "$line" =~ bcm2835 ]] && [[ ! "$line" =~ vc4 ]]; then
        USB_RECORD_CARD="${BASH_REMATCH[1]}"
        USB_RECORD_NAME=$(echo "$line" | sed 's/card [0-9]*: //' | cut -d'[' -f2 | cut -d']' -f1)
        break
    fi
done < <(arecord -l 2>/dev/null)

echo ""
if [ -n "$USB_PLAYBACK_CARD" ]; then
    print_success "USB Speaker found: Card $USB_PLAYBACK_CARD ($USB_PLAYBACK_NAME)"
else
    print_warning "No USB speaker detected - will try all cards"
fi

if [ -n "$USB_RECORD_CARD" ]; then
    print_success "USB Microphone found: Card $USB_RECORD_CARD ($USB_RECORD_NAME)"
else
    print_warning "No USB microphone detected - will try all cards"
fi

# ============================================================================
print_header "Step 4: Configuring Default Audio Devices"
# ============================================================================

# Determine which cards to use
PLAY_CARD="${USB_PLAYBACK_CARD:-0}"
REC_CARD="${USB_RECORD_CARD:-0}"

print_info "Setting playback to card $PLAY_CARD"
print_info "Setting recording to card $REC_CARD"

# Create ALSA config
cat > ~/.asoundrc << EOF
# PLUTO Audio Configuration
# Generated by audio_setup.sh

# Default playback device (Speaker)
pcm.speaker {
    type hw
    card $PLAY_CARD
    device 0
}

# Default recording device (Microphone)
pcm.mic {
    type hw
    card $REC_CARD
    device 0
}

# Default PCM - asymmetric (different devices for playback/capture)
pcm.!default {
    type asym
    playback.pcm "plug:speaker"
    capture.pcm "plug:mic"
}

# Fallback with software mixing
pcm.dmixed {
    type dmix
    ipc_key 1024
    slave {
        pcm "hw:$PLAY_CARD,0"
        rate 44100
    }
}

pcm.dsnooped {
    type dsnoop
    ipc_key 1025
    slave {
        pcm "hw:$REC_CARD,0"
        rate 44100
    }
}

pcm.duplex {
    type asym
    playback.pcm "dmixed"
    capture.pcm "dsnooped"
}

# Control device
ctl.!default {
    type hw
    card $PLAY_CARD
}
EOF

print_success "Audio configuration saved to ~/.asoundrc"

# ============================================================================
print_header "Step 5: Setting Volume to Maximum"
# ============================================================================

# Set playback volume
amixer -c $PLAY_CARD set Master 100% unmute 2>/dev/null || \
amixer -c $PLAY_CARD set Speaker 100% unmute 2>/dev/null || \
amixer -c $PLAY_CARD set PCM 100% unmute 2>/dev/null || \
amixer -c $PLAY_CARD set Headphone 100% unmute 2>/dev/null || \
print_warning "Could not set playback volume automatically"

# Set capture volume
amixer -c $REC_CARD set Capture 100% cap 2>/dev/null || \
amixer -c $REC_CARD set Mic 100% cap 2>/dev/null || \
print_warning "Could not set capture volume automatically"

print_success "Volume set to maximum"

# ============================================================================
print_header "Step 6: Testing Speaker"
# ============================================================================

echo ""
print_info "Playing test sound on card $PLAY_CARD..."
echo ""

# Try multiple methods
SPEAKER_WORKS=false

# Method 1: Direct hardware
if speaker-test -D hw:$PLAY_CARD,0 -t sine -f 440 -l 1 -p 1 2>/dev/null; then
    SPEAKER_WORKS=true
    print_success "Speaker test PASSED (hw:$PLAY_CARD,0)"
fi

# Method 2: Plug device
if [ "$SPEAKER_WORKS" = false ]; then
    if speaker-test -D plughw:$PLAY_CARD,0 -t sine -f 440 -l 1 -p 1 2>/dev/null; then
        SPEAKER_WORKS=true
        print_success "Speaker test PASSED (plughw:$PLAY_CARD,0)"
    fi
fi

# Method 3: Default
if [ "$SPEAKER_WORKS" = false ]; then
    if speaker-test -t sine -f 440 -l 1 -p 1 2>/dev/null; then
        SPEAKER_WORKS=true
        print_success "Speaker test PASSED (default)"
    fi
fi

# Method 4: Try each card
if [ "$SPEAKER_WORKS" = false ]; then
    for card in 0 1 2 3; do
        if speaker-test -D hw:$card,0 -t sine -f 440 -l 1 -p 1 2>/dev/null; then
            SPEAKER_WORKS=true
            PLAY_CARD=$card
            print_success "Speaker test PASSED on card $card"
            break
        fi
    done
fi

if [ "$SPEAKER_WORKS" = false ]; then
    print_error "Speaker test FAILED on all devices"
    print_warning "Check physical connections and try: alsamixer"
fi

# ============================================================================
print_header "Step 7: Testing Microphone"
# ============================================================================

echo ""
print_info "Recording 3 seconds from card $REC_CARD..."
print_info "Please speak into the microphone NOW!"
echo ""

TEST_FILE="/tmp/pluto_mic_test.wav"
MIC_WORKS=false

# Method 1: Direct hardware
if arecord -D hw:$REC_CARD,0 -d 3 -f cd "$TEST_FILE" 2>/dev/null; then
    MIC_WORKS=true
fi

# Method 2: Plug device
if [ "$MIC_WORKS" = false ]; then
    if arecord -D plughw:$REC_CARD,0 -d 3 -f cd "$TEST_FILE" 2>/dev/null; then
        MIC_WORKS=true
    fi
fi

# Method 3: Default
if [ "$MIC_WORKS" = false ]; then
    if arecord -d 3 -f cd "$TEST_FILE" 2>/dev/null; then
        MIC_WORKS=true
    fi
fi

if [ "$MIC_WORKS" = true ] && [ -f "$TEST_FILE" ]; then
    FILE_SIZE=$(stat -f%z "$TEST_FILE" 2>/dev/null || stat -c%s "$TEST_FILE" 2>/dev/null || echo "0")
    if [ "$FILE_SIZE" -gt 1000 ]; then
        print_success "Microphone recording successful ($FILE_SIZE bytes)"
        
        echo ""
        print_info "Playing back your recording..."
        aplay -D hw:$PLAY_CARD,0 "$TEST_FILE" 2>/dev/null || \
        aplay -D plughw:$PLAY_CARD,0 "$TEST_FILE" 2>/dev/null || \
        aplay "$TEST_FILE" 2>/dev/null || \
        print_warning "Could not play back recording"
    else
        print_warning "Recording file is empty - microphone may not be working"
    fi
else
    print_error "Microphone test FAILED"
fi

rm -f "$TEST_FILE"

# ============================================================================
print_header "Step 8: Save Configuration for Pluto"
# ============================================================================

# Create a config file for Python to read
PLUTO_AUDIO_CONFIG="$HOME/pluto-v2/audio_config.txt"
mkdir -p "$HOME/pluto-v2"

cat > "$PLUTO_AUDIO_CONFIG" << EOF
# Pluto Audio Configuration
# Auto-generated by audio_setup.sh
PLAYBACK_CARD=$PLAY_CARD
PLAYBACK_DEVICE=hw:$PLAY_CARD,0
RECORD_CARD=$REC_CARD
RECORD_DEVICE=hw:$REC_CARD,0
EOF

print_success "Pluto audio config saved to $PLUTO_AUDIO_CONFIG"

# ============================================================================
print_header "🎉 Audio Setup Complete!"
# ============================================================================

echo ""
echo -e "${GREEN}════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  Configuration Summary${NC}"
echo -e "${GREEN}════════════════════════════════════════════════════════════${NC}"
echo ""
echo "  Speaker:    Card $PLAY_CARD (hw:$PLAY_CARD,0)"
echo "  Microphone: Card $REC_CARD (hw:$REC_CARD,0)"
echo ""

if [ "$SPEAKER_WORKS" = true ]; then
    echo -e "  Speaker Test:    ${GREEN}✅ PASSED${NC}"
else
    echo -e "  Speaker Test:    ${RED}❌ FAILED${NC}"
fi

if [ "$MIC_WORKS" = true ]; then
    echo -e "  Microphone Test: ${GREEN}✅ PASSED${NC}"
else
    echo -e "  Microphone Test: ${RED}❌ FAILED${NC}"
fi

echo ""
echo "Next steps:"
echo "  1. Run Pluto: ./run_online.sh"
echo ""

if [ "$SPEAKER_WORKS" = false ] || [ "$MIC_WORKS" = false ]; then
    echo -e "${YELLOW}Troubleshooting:${NC}"
    echo "  • Check USB cable connections"
    echo "  • Try a different USB port"
    echo "  • Run: alsamixer (press F6 to select card)"
    echo "  • Reboot: sudo reboot"
    echo ""
fi
